theme: jekyll-theme-minimal
title: Rethinking Evidence in African American Digital Studies
description: A workshop  
1:45 - 4:45 PM, January 6, 2018  
Studio@Butler  
208b Butler Library  
Columbia University  
Butler Library  
535 West 114th St.  
New York, NY 10027  
